### ISSUE TITLE
Dictionary changed size during iteration when removing a callback

### ISSUE THREAD

**Issue by jonathanfoster** [fizista/micropython-mcron#4]
**Describe the bug**
When removing a callback, if no other callbacks exist for that period step, then `remove` attempts to remove the period step from `period_data` resulting in a runtime error, `dictionary changed size during iteration`. This is because `remove` is currently iterating over `period_data`.

The bug is caused by [this line of code](https://github.com/fizista/micropython-mcron/blob/master/mcron/__init__.py#L125).

**To Reproduce**
```python
mcron.init_timer()
mcron.insert(mcron.PERIOD_DAY, {7 * 60 * 60}, "do_something", do_something_cb)
mcron.remove("do_something")
```

**Comment by fizista** [comment]
Thank you for finding this error in the code. I have already corrected it.

**Comment by jonathanfoster** [comment]
@fizista I'm still getting a `dictionary changed size during iteration`. Now it's coming from https://github.com/fizista/micropython-mcron/blob/master/mcron/__init__.py#L131.
